services:
  - type: web
    name: nexume-ats-api
    runtime: python
    rootDir: Resume-ATS-Checker-main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: GEMINI_API_KEY
        sync: false
